### PR TITLE
Add Forza Horizon 2 server ip address

### PR DESCRIPTION
**Pull request by TechSasuke**

### CODE REVIEW

**Comment by craftycodie** [comment]
I'm not sure we should be adding localhost servers here
we could instead, add an option to xenia netplay config to allow you to provide localhost as an LSP for all titles, if there was a reason to do so

What's the use case here?

**Comment by TechSasuke** [comment]
The case here is that the game works with P2P just like all other Forzas, but this specific one needs to recognize that it can connect with the LSP to be able to play Online (Online Road Trip), and I'm studying this and would like to try to add a localhost server to try and get the game to recognize Localhost as the LSP, which should theoretically work.

**Comment by craftycodie** [comment]
Wouldn't the game realise that there's no web server running locally?

**Comment by TechSasuke** [comment]
As far as i know for Online Road Trip the game wouldn't check that, but for other functions that requires a LSP probably.

**Comment by AdrianCassar** [comment]
I agree with codie, xenia web-services shouldn't point to local servers on production (this repo). Feel free to setup xenia web-services and test the outcome of adding an LSP entry. For example, adding an LSP entry like this for MW2 completely breaks MP.

The description key is actually a filter, i checked FH2 and it doesn't seem to have one so adding a description may have unintended consequences.

I tested this LSP entry and it didn't seem to have any affect on Online Road Trip. Furthermore, you'd want to determine what ports the server would be running on.

**Comment by TechSasuke** [comment]
I understood. I didn't quite understand how to configure Xenia Web-Services in my PC and i'm actually still studying how the online part of this game works so setup Xenia Web-Services to test would help a lot.

**Pull request closed without merging**
